library(stringr)

data <- read.csv("tweets_data.csv")
tweets <- data[,4]
tweet <- str_replace_all(tweets, "http(s)?://[^[:blank:]]+", "")
tweetnew <- str_replace_all(tweet, "#[^[:blank:]]+", "")
tweetnew <- str_replace_all(tweetnew, "[$][^[:blank:]]+", "")
tweetnew <- str_replace_all(tweetnew, "[^[:blank:]]+\\.com[^[:blank:]]+", "")
tweetnew <- str_replace_all(tweetnew, ">+", "")
tweetnew <- str_replace_all(tweetnew, "for.+[Hh]elp", "")
tweetnew <- str_replace_all(tweetnew, "for.+&", "")
tweetnew <- str_replace_all(tweetnew, "for$", "")
tweetnew <- str_replace_all(tweetnew, "^[:blank:]+", "")
tweetnew <- str_replace_all(tweetnew, "…", "")
tweetnew <- str_replace_all(tweetnew, "\\(", "")
tweetnew <- str_replace_all(tweetnew, "\\)", "")
tweetnew <- str_replace_all(tweetnew, "@", "")
tweetnew <- str_replace_all(tweetnew, "%", "")
tweetnew <- str_replace_all(tweetnew, "\\+", "")
tweetnew <- str_replace_all(tweetnew, "–", "")
tweetnew <- str_replace_all(tweetnew, "´", "")
tweetnew <- str_replace_all(tweetnew, "\"", "")
tweetnew <- str_replace_all(tweetnew, "—", "")
tweetnew <- str_replace_all(tweetnew, "\\*", "")
tweetnew <- str_replace_all(tweetnew, "[:blank:][:blank:]+", " ")
data[,4] <- tweetnew
write.csv(data, "newtweet.csv")
